---
title: "Data_cleaning"
output: html_document
date: "2025-09-21"
---

```{r library}
library(here)
library(readr)
library(tidyverse)
```
others data
```{r set up file path(relative)}
rm(list = ls())
wd <- "analysis/pnwandmore/data/other_treerings/direct_searching/others/doi_10_5061_dryad_k5k9074__v20190226/Raw_Ring_Widths_012118/Raw_Ring_Widths_012118"
wo <- 'analysis/pnwandmore/input/other_tree_rings/direct_searching/others'
wl <- "analysis/pnwandmore/data/other_treerings/direct_searching/others/doi_10_5061_dryad_k5k9074__v20190226/Tree_Info_BAI_012118/Tree_Info_BAI_012118"
```

```{r pressure, echo=FALSE}
rawRingDatas <- list.files(here(wd),pattern="avgRingWidth.*",recursive=TRUE,full.names=FALSE)
```

```{r data cleaning}
for (d in 1:length(rawRingDatas)) {
  df_name <- rawRingDatas[d]
  title <- paste0(substr(df_name,1,2),"_",substr(df_name,4,7))
  
  treeinfofile <- list.files(here(wl),pattern=paste0(title,"_treeinfobai",".*\\.csv$"),full.names=FALSE)[1]
  
  
  rawRingData <- read.csv(here(wd,df_name))
  treeinfo <- read.csv(here(wl,treeinfofile)) %>%
    select(Tag,Lat,Long)
  
  rawRingData_long <- rawRingData %>%
  select(-X)%>%
  pivot_longer(
    cols = starts_with("X"),
    names_to = "years",
    names_prefix = "X",
    values_to = "Ring_width(mm)") %>%
  select(-Species,-Elev) %>%
    left_join(treeinfo,by="Tag")

  head(rawRingData_long)
  write.csv(rawRingData_long,here(wo,df_name))
}
```


Alberta data
```{r directory} 
alwd <- "analysis/pnwandmore/data/other_treerings/direct_searching/Alberta/dataCite/RawtreeRing/whiteSpruce1983-2016/treering_width.csv"
alwo <- 'analysis/pnwandmore/input/other_tree_rings/direct_searching/Alberta'
```

```{r data input}
alrrd <- read.csv(here(alwd))
```

```{r cleaning and saving}
alrrd <- alrrd %>%
  select(id,year,trw,Latitude,Longitude)%>%
  rename("Ring_width(mm)" = trw,
         Lat = Latitude,
         Long = Longitude,
         Tag = id,
         years = year)

write.csv(alrrd,here(alwo,"treering_width.csv"))
```

Arizona datasearch
```{r directory}
arw <- "analysis/pnwandmore/data/other_treerings/direct_searching/Arizona/datasearch/rawTreeRing/bog_tree/bog_tree_ring_data.txt"
arwo <- 'analysis/pnwandmore/input/other_tree_rings/direct_searching/Arizona'
```

```{r data cleaning}
Lat <- tibble(Lat = 64.6408)
Long <- tibble(Long = 	-148.3334833)
arrrd <- read.table(here(arw),sep="\t",skip = 2,col.names = c("years","Tag","Tree location","Ring_width","Temperature (ºC, Growing Season: May, June, July, Aug)","Precipitation (mm, Growing Season: May, June, July, Aug)")) %>%
  select(years,Tag,Ring_width)%>%
  rename("Ring_width(mm)"=Ring_width)%>%
  bind_cols(Lat,Long)

write.csv(arrrd,here(arwo,"bog_tree_ring_data.csv"))
```

```{r}
arw1 <- "analysis/pnwandmore/data/other_treerings/direct_searching/Arizona/datasearch/rawTreeRing/PIPOcores518/PIPOCores518RingWidths.txt"
arwlgeo <- "analysis/pnwandmore/data/other_treerings/direct_searching/Arizona/datasearch/rawTreeRing/PIPOcores518/PIPOCores518Meta.txt"

geoloc <- read_tsv(here(arwlgeo)) %>%
  select(CORE_CN,LON,LAT)
arrrd1 <- read.table(here(arw1),sep="\t",skip=1,
                     col.names = c("Ring_width","years","CORE_CN")) %>%
  left_join(geoloc,by = "CORE_CN")%>%
  rename(Lat = LAT,
         Lon = LON,
         "Ring_width(mm)"=Ring_width,
         Tag = CORE_CN)
write.csv(arrrd1,here(arwo,"PIPOCores518RingWidths.csv"))
```

Arizona dataCite
```{r}
arc <- "analysis/pnwandmore/data/other_treerings/direct_searching/Arizona/dataCite/RawTreeRing/speciesResponse/core_data_22dec2023 (1)/core_data_22dec2023 (1).csv"
arc1 <- read.csv(here(arc)) %>%
  select(Year,Series,RW,x,y)%>%
  rename(years = Year,
         Tag = Series,
         "Ring_width(mm)"=RW,
         Lat = x,
         Lon = y)
write.csv(arc1,here(arwo,"core_data_22dec2023.csv"))
```

BC datasearch
```{r} 
wdb <- "analysis/pnwandmore/data/other_treerings/direct_searching/BC/datasearch/RawTreeRing/EN22_Tree_Ring_Widths.tab"
savebc<-'analysis/pnwandmore/input/other_tree_rings/direct_searching/Bc'

bcdata <- read_tsv(here(wdb),skip = 52) %>%
  rename(Lat=Latitude,
         Long=Longitude,
         "Ring_width(mm)"="TRW [mm]" ,
         years="Age [a AD/CE]",
         Tag="Subsample ID")%>%
  select(Tag,Lat,Long,years,"Ring_width(mm)")
write.csv(bcdata,here(savebc,"EN22_Tree_Ring_Widths.csv"))
#head(bcdata)
```

Colorado datasearch
```{r} 
wdco <-"analysis/pnwandmore/data/other_treerings/direct_searching/colorado/datasearch/rawTreeRing/US_State/RDS-2024-0066/Data/ring_widths_LPP.csv"
spatialco <- "analysis/pnwandmore/data/other_treerings/direct_searching/colorado/datasearch/rawTreeRing/US_State/RDS-2024-0066/Data/spatial_LPP.csv"
growthco <- "analysis/pnwandmore/data/other_treerings/direct_searching/colorado/datasearch/rawTreeRing/US_State/RDS-2024-0066/Data/growth_LPP.csv"
saveco<-"analysis/pnwandmore/input/other_tree_rings/direct_searching/Colorado/US_state"


cospatial <- read_csv(here(spatialco))
cogrowth <- read_csv(here(growthco))
codata <- read_csv(here(wdco))%>%
  pivot_longer(cols=-1,
               names_to = "TREE_ID",
               values_to = "Ring_width(mm)")%>%
  left_join(cogrowth,by="TREE_ID")%>%
  left_join(cospatial,by=c("STATE","PROV"))%>%
  select(YEAR,TREE_ID,"Ring_width(mm)",LAT,LONG)%>%
  rename(years=YEAR,
         Tag=TREE_ID,
         Lat=LAT,
         Long=LONG)
  
write.csv(codata,here(saveco,"ring_widths_LPP.csv"))
```

idaho dataCite
