---
title: "visualization"
output: html_document
date: "2025-09-16"
---

```{r loading package}
library(rstan)
```

```{r setup, include=FALSE}
util <- new.env()
source('mcmc_analysis_tools_rstan.R', local=util)
source('mcmc_visualization_tools.R', local=util)
source('confronting_with_real_data.R')
```

```{r cars}
diagnostics <- util$extract_hmc_diagnostics(fit)
util$check_all_hmc_diagnostics(diagnostics)
samples <- util$extract_expectand_vals(fit)
samples3 <- util$extract_expectand_vals(fit3)
samples5 <- util$extract_expectand_vals(fit5)
util$check_all_expectand_diagnostics(samples)
```

```{r retro check}
par(mfrow=c(1,1))
util$plot_hist_quantiles(samples,'y_rep',baseline_values = stan_data$y)
```

```{r retro by species}
pred_names <- sapply(1:stan_data$Nf,function(n) paste0('y_rep[',n,']'))
util$plot_conditional_mean_quantiles(samples,pred_names,stan_data$tree_sp,1,7,1,stan_data$y,residual = FALSE,xlab="species",ylab="conditional mean of tree growth (mm)")
```
```{r retro by radius}
util$plot_conditional_mean_quantiles(samples,pred_names,stan_data$ra,2,12,2,stan_data$y,residual=FALSE,xlab="focal radius (*10 cm)",ylab="conditional mean of tree growth (mm)")
```

```{r sigma visualization}
# util$plot_expectand_pushforward(samples[["sigma"]], 25,
#      display_name=bquote(sigma~"(standard deviation of tree growth)"),
#      #baseline=sigma,
#      baseline_col=util$c_mid_teal) 
#08 vs avg3
par(mfrow=c(1,1))
# util$plot_line_hists(samples[["sigma"]],samples3[["sigma"]],0.45,0.65, 0.01,xlab=bquote(sigma~"(standard deviation of tree growth)"))
# text(0.45,1000,1.25,label="2008",pos=4,col="black")
# text(0.52,1000,1,label="avg(06,07,08)",pos=4,col=util$c_mid_teal)
plot(0,type="n",xlim=c(0.45,0.65),ylim=c(0,1300),
     xlab=bquote(sigma~"(standard deviation of tree growth)"),
     ylab="counts")
util$plot_line_hist(samples[["sigma"]],0.45,0.65,0.01,col="black",add=TRUE)
util$plot_line_hist(samples3[["sigma"]],0.45,0.65,0.01,col=util$c_mid_teal,add=TRUE)
util$plot_line_hist(samples5[["sigma"]],0.45,0.65,0.01,col=util$c_dark,add=TRUE)
text(0.45,1000,1.25,label="2008",pos=4,col="black")
text(0.52,1000,1,label="avg(06,07,08)",pos=4,col=util$c_mid_teal)
text(0.52,700,1,label="avg(04,05,06,07,08)",pos=4,col=util$c_dark)

#08 vs avg5
# util$plot_line_hists(samples[["sigma"]],samples5[["sigma"]],0.45,0.65, 0.01,xlab=bquote(sigma~"(standard deviation of tree growth)"))
# text(0.45,1000,1.25,label="2008",pos=4,col="black")
# text(0.52,1000,1,label="avg(04,05,06,07,08)",pos=4,col=util$c_dark_teal)
```

```{r y0 visualization}
# util$plot_expectand_pushforward(samples[["y0"]], 25,
#      display_name="y0(baseline growth (mm))",
#      #baseline=y0,
#      baseline_col=util$c_mid_teal) 
on.exit(dev.off())
par(mfrow=c(2,3))
for(i in 1:6){
  util$plot_expectand_pushforward(samples[[paste0('y0[',i,']')]], 20, paste0('y0[',i,'](baseline growth mm)'))
  abline(v = mu[i])
}
```

```{r k visualization}
# util$plot_expectand_pushforward(samples[["k"]], 25,
#      display_name=bquote(kappa~"(strength of the species in competition)"),
#      #baseline=k,
#      baseline_col=util$c_mid_teal)

# util$plot_line_hists(samples[["k"]],samples3[["k"]],0,1,0.01,xlab=bquote(kappa~"(strength of the species in competition)"))
# text(0.2,70,1.25,label="2008",pos=4,col="black")
# text(0.5,20,1.25,label="avg(06,07,08)",pos=4,col=util$c_mid_teal)

plot(0,type="n",
     xlim = c(0,1),xlab=bquote(kappa~"(strength of the species in competition)"),
     ylim = c(0,400),ylab="Counts")
util$plot_line_hist(samples[["k"]],0,1,0.05,col="black",add=TRUE)
util$plot_line_hist(samples3[["k"]],0,1,0.05,col=util$c_mid_teal,add=TRUE)
util$plot_line_hist(samples5[["k"]],0,1,0.05,col=util$c_dark,add=TRUE)
text(0.2,300,0.5,label="2008",pos=4,col="black")
text(0,200,0.5,label="avg(06,07,08)",pos=4,col=util$c_mid_teal)
text(0.5,100,0.5,label="avg(04,05,06,07,08)",pos=4,col=util$c_dark)

# util$plot_line_hists(samples[["k"]],samples5[["k"]],0,1,0.01,xlab=bquote(kappa~"(strength of the species in competition)"))
# text(0.2,70,1.25,label="2008",pos=4,col="black")
# text(0.5,20,1.25,label="avg(04,05,06,07,08)",pos=4,col=util$c_dark_teal)
```

```{r r visualization}
# util$plot_expectand_pushforward(samples[["r"]], 25,
#      display_name="r (scaling factor of basel area)",
#      #baseline=r,
#      baseline_col=util$c_mid_teal) 
on.exit(dev.off())
par(mfrow=c(2,3))
for(i in 1:6){
  util$plot_expectand_pushforward(samples[[paste0('r[',i,']')]], 20, paste0('r[',i,'](scaling factor of basel area)'))
  abline(v = mu[i])
}
```

```{r beta visualization}
# util$plot_expectand_pushforward(samples[["beta"]], 25,
#      display_name=bquote(beta~"(Impact of inter-species competition)"),
#      #baseline=beta,
#      baseline_col=util$c_mid_teal)
on.exit(dev.off())
par(mfrow=c(2,3))
for (i in 1:6) {
  util$plot_expectand_pushforward(samples[[paste0("beta[",i,"]")]],20,bquote(beta[.(i)]~"(Impact of Interspecies competition)"))
}
```

```{r hyperparame visualization}
par(mfrow=c(1,1))
util$plot_expectand_pushforward(samples[["log_y0_mu"]],20,display_name = bquote(log_y0_mu),
                                baseline_col = util$c_mid_teal)


util$plot_expectand_pushforward(samples[["log_y0_tau"]],20,display_name = bquote(log_y0_tau),
                                baseline_col = util$c_mid_teal)


util$plot_expectand_pushforward(samples[["log_beta_mu"]],20,display_name = bquote(log_beta_mu),
                                baseline_col = util$c_mid_teal)


util$plot_expectand_pushforward(samples[["log_beta_tau"]],20,display_name = bquote(log_beta_tau),
                                baseline_col = util$c_mid_teal)


util$plot_expectand_pushforward(samples[["logodds_r_mu"]],20,display_name = bquote(logodds_mu),
                                baseline_col = util$c_mid_teal)

util$plot_expectand_pushforward(samples[["logodds_r_tau"]],20,display_name = bquote(logodds_tau),
                                baseline_col = util$c_mid_teal)
```

```{r individual parameters visual}
par(mfrow=c(1,3))
util$plot_disc_pushforward_quantiles(samples, paste0('y0[',1:6,']'),xlab="y0")
util$plot_disc_pushforward_quantiles(samples3, paste0('y0[',1:6,']'),xlab="y0(avg(06,07,08)")
util$plot_disc_pushforward_quantiles(samples5, paste0('y0[',1:6,']'),xlab="y0(avg(04,05,06,07,08)")

util$plot_disc_pushforward_quantiles(samples, paste0('beta[',1:6,']'),xlab="beta")
util$plot_disc_pushforward_quantiles(samples3, paste0('beta[',1:6,']'),xlab="beta(avg(06,07,08)")
util$plot_disc_pushforward_quantiles(samples5, paste0('beta[',1:6,']'),xlab="beta(avg(04,05,06,07,08)")

util$plot_disc_pushforward_quantiles(samples, paste0('r[',1:6,']'),xlab="r")
util$plot_disc_pushforward_quantiles(samples3, paste0('r[',1:6,']'),xlab="r(avg(06,07,08)")
util$plot_disc_pushforward_quantiles(samples5, paste0('r[',1:6,']'),xlab="r(avg(04,05,06,07,08))")
```

```{r individual parameters altegether}
param_names <- c(
  paste0("y0[", 1:6, "]"),
  paste0("beta[", 1:6, "]"),
  paste0("r[", 1:6, "]"),
  "k",
  "sigma"
)

util$plot_disc_pushforward_quantiles(samples, param_names,xlab="individual parameters")

```
