---
title: "Work on Cauchy-shocks "
toc: true
number-sections: true
highlight: pygments
pdf-engine: lualatex
format:
  html:
    html-math-method: katex
    theme:
      - lux
      - custom.scss
    standalone: true
    embed-resources: true
    code-overflow: wrap
    linkcolor: "#B97C7C"
    fontsize: '11pt'
    code-block-border-left: "#8F2727"
    code-block-bg: "#f8f8f8"
    highlight-style: github
  pdf:
    keep-tex: true
    fig-width: 4
    fig-height: 4
    code-overflow: wrap
    monofont: 'Latin Modern Mono'
    monofontoptions:
      - Scale=0.5
format-links: false
knitr:
  opts_chunk:
    comment: ''
    cache.lazy: FALSE
  opts_knit:
    global.par: TRUE
geometry:
  - top=20mm
  - left=20mm
  - bottom=20mm
  - right=20mm
---

```{css, echo=FALSE}
.cell-output { border-left: #B97C7C 2px solid; border-radius: 6px;}
```


```{r}
#| echo: false
#| warning: false
#| message: false
wd <- "~/projects/climategrowthshifts/analysis/pnwandmore"
setwd(file.path(wd, 'model/shocks'))
util <- new.env()
source('mcmc_analysis_tools_rstan.R', local=util)
source('mcmc_visualization_tools.R', local=util)
# source('functions/custom_functions.R', local=util)
setwd(wd)
library(rstan)
options(mc.cores = parallel::detectCores())

chunk_hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- chunk_hook(x, options)
  paste0("\\linespread{0.5}\n", x, "\n\n\\linespread{2}")
})

par(family="serif", las=1, bty="l",
    cex.axis=0.8, cex.lab=0.85, cex.main=1,
    xaxs="i", yaxs="i", mar = c(5, 5, 3, 1))

logit <- function(x) log(x/(1-x))
inv_logit <- function(x) return(exp(x) / (1 + exp(x)))
```

```{r}
data <- readRDS(file = file.path(wd, 'output', 'model', 'data_15nov2025_az592_az628.rds'))

if(FALSE){
  fit <- stan(file=file.path(wd, 'model', 'stan', 'model9_marginalshocks_zerotauinner_cauchy.stan'),
            data=data, seed=5838293, chains = 4,
            warmup=1000, iter=2024, refresh=10)
  saveRDS(fit, file.path(wd, 'model/shocks/output/marginal', 'fit_cauchy1.rds'))
}else{
  fit <- readRDS(file.path(wd, 'model/shocks/output/marginal', 'fit_cauchy1.rds'))
}

```

## Diagnostics

```{r}

samples <- util$extract_expectand_vals(fit)
base_samples <- util$filter_expectands(samples,
                                       c('alpha', 
                                         'beta_gdd', 'beta_sm', 'beta_vpd',
                                         'rho_sh', 'gamma_sh',
                                         'rho_sp', 'gamma_sp',
                                         'sigma', 
                                         'phi_sck', 'omega_conc_sck', 'omega_nonconc_sck'),
                                       check_arrays = TRUE)
util$check_all_expectand_diagnostics(base_samples)

```

## Retrodictive check

### Stand 1

```{r}
#| fig-width: 8
#| fig-height: 7

par(mfcol = c(3,2))
for(t in 1:8){
  idxs_t <- data$tree_start_idxs[t]:data$tree_end_idxs[t]
  names <- sapply(idxs_t,
                  function(x) paste0('log_rw_pred[', x, ']'))
  util$plot_conn_pushforward_quantiles(samples, names, data$years[idxs_t],
                                       xlab="", ylab='log_rw_pred', main = paste0('Tree ', data$uniq_tree_ids[t]),
                                       display_ylim=c(-10, 2), display_xlim = c(1980, 2021))
  points(data$years[idxs_t], data$log_rw_obs[idxs_t], pch=16, cex=1, col="white")
  points(data$years[idxs_t], data$log_rw_obs[idxs_t], pch=16, cex=0.6, col="black")
  abline(v = 2002, lty = 3, col="darkgrey")
  
  
  names <- sapply(idxs_t,
                  function(x) paste0('delta_sck[', x, ']'))
  util$plot_conn_pushforward_quantiles(samples, names, data$years[idxs_t],
                                       xlab="", ylab='delta_sck', 
                                       display_ylim=c(-10, 2), display_xlim = c(1980, 2021))
  abline(v = 2002, lty = 3, col="darkgrey")
  
  names <- sapply(1:43,
                  function(x) paste0('f_sh[', data$stand_idxs[t],',',x, ']'))
  util$plot_conn_pushforward_quantiles(samples, names, data$all_years,
                                       xlab="", ylab='Stand GP', 
                                       display_ylim=c(-2, 2), display_xlim = c(1980, 2021))
  abline(v = 2002, lty = 3, col="darkgrey")
}

```

### Stand 2

```{r}
#| fig-width: 8
#| fig-height: 7

par(mfcol = c(3,2))
for(t in 41:48){
  idxs_t <- data$tree_start_idxs[t]:data$tree_end_idxs[t]
  names <- sapply(idxs_t,
                  function(x) paste0('log_rw_pred[', x, ']'))
  util$plot_conn_pushforward_quantiles(samples, names, data$years[idxs_t],
                                       xlab="", ylab='log_rw_pred', main = paste0('Tree ', data$uniq_tree_ids[t]),
                                       display_ylim=c(-10, 2), display_xlim = c(1980, 2021))
  points(data$years[idxs_t], data$log_rw_obs[idxs_t], pch=16, cex=1, col="white")
  points(data$years[idxs_t], data$log_rw_obs[idxs_t], pch=16, cex=0.6, col="black")
  abline(v = 2002, lty = 3, col="darkgrey")
  
  
  names <- sapply(idxs_t,
                  function(x) paste0('delta_sck[', x, ']'))
  util$plot_conn_pushforward_quantiles(samples, names, data$years[idxs_t],
                                       xlab="", ylab='delta_sck', 
                                       display_ylim=c(-10, 2), display_xlim = c(1980, 2021))
  abline(v = 2002, lty = 3, col="darkgrey")
  
  names <- sapply(1:43,
                  function(x) paste0('f_sh[', data$stand_idxs[t],',',x, ']'))
  util$plot_conn_pushforward_quantiles(samples, names, data$all_years,
                                       xlab="", ylab='Stand GP', 
                                       display_ylim=c(-2, 2), display_xlim = c(1980, 2021))
  abline(v = 2002, lty = 3, col="darkgrey")
}

```

## Posterior inference

# Quickly look at posteriors

```{r}
nf <- layout(
  matrix(c(1,1,1,2,2,2,
           3,3,4,4,5,5), 
         ncol=6, byrow=TRUE)
)
util$plot_expectand_pushforward(samples[['sigma']], 50,
                                flim = c(0,0.5), 
                                display_name=expression(tau[shock]^inner))
xs <- seq(0, 2, 0.01)
ys <- dnorm(xs, 0, log(1.1) / 2.57)
lines(xs, ys, lwd=2.7, col='white')
lines(xs, ys, lwd=1.7, col=util$c_mid_teal)

util$plot_expectand_pushforward(samples[['outer_tau_sck']], 50,
                                flim = c(0,2), 
                                display_name=expression(tau[shock]^outer))
xs <- seq(0, 2, 0.01)
ys <- dnorm(xs, 0, 1 / 2.57)
lines(xs, ys, lwd=2.7, col='white')
lines(xs, ys, lwd=1.7, col=util$c_mid_teal)

util$plot_expectand_pushforward(samples[['phi_sck[1]']], 50,
                                flim = c(0,0.5), 
                                display_name=expression(phi[schock]))
for(s in 2:data$N_stands){
  util$plot_expectand_pushforward(samples[[paste0('phi_sck[',s,']')]], 50,
                                  flim = c(0,0.5), 
                                  display_name=expression(phi[schock]), add = T)
}
xs <- seq(0, 0.5, 0.01)
ys <- dbeta(xs, 2, 20)
lines(xs, ys, lwd=2.7, col='white')
lines(xs, ys, lwd=1.7, col=util$c_mid_teal)

util$plot_expectand_pushforward(samples[['omega_conc_sck']], 50,
                                flim = c(0,1), 
                                display_name=expression(omega[shock]^concordant))
xs <- seq(0, 1, 0.01)
ys <- dbeta(xs, 230, 14)
lines(xs, ys, lwd=2.5, col='white')
lines(xs, ys, lwd=1.7, col=util$c_mid_teal)
util$plot_expectand_pushforward(samples[['omega_nonconc_sck']], 50,
                                flim = c(0,0.5), 
                                display_name=expression(omega[shock]^nonconcordant))
xs <- seq(0, 1, 0.01)
ys <- dbeta(xs, 1, 20)
lines(xs, ys, lwd=2.7, col='white')
lines(xs, ys, lwd=1.7, col=util$c_mid_teal)
```

## Zeros that are not zeros

```{r}
data <- readRDS(file = file.path(wd, 'output', 'model', 'data_15nov2025_az592_az628.rds'))
data$rw_obs <- ifelse(data$log_rw_obs == log(1e-4), 0, exp(data$log_rw_obs))

if(FALSE){
  fit <- stan(file=file.path(wd, 'model', 'stan', 'model9_marginalshocks_zerotauinner_cauchy_censoring.stan'),
            data=data, seed=5838293, chains = 4,
            warmup=1000, iter=2024, refresh=10)
  saveRDS(fit, file.path(wd, 'model/shocks/output/marginal', 'fit_cauchy2.rds'))
}else{
  fit <- readRDS(file.path(wd, 'model/shocks/output/marginal', 'fit_cauchy2.rds'))
}

```

```{r}

samples <- util$extract_expectand_vals(fit)
base_samples <- util$filter_expectands(samples,
                                       c('alpha', 
                                         'beta_gdd', 'beta_sm', 'beta_vpd',
                                         'rho_sh', 'gamma_sh',
                                         'rho_sp', 'gamma_sp',
                                         'sigma', 
                                         'phi_sck', 'omega_conc_sck', 'omega_nonconc_sck'),
                                       check_arrays = TRUE)
util$check_all_expectand_diagnostics(base_samples)

```

### Stand 1

```{r}
#| fig-width: 8
#| fig-height: 7

par(mfcol = c(3,2))
for(t in 1:8){
  # idxs_t <- data$tree_start_idxs[t]:data$tree_end_idxs[t]
  idxs_t <- data$tree_start_idxs[t]:(data$tree_start_idxs[t]+1)
  names <- sapply(idxs_t,
                  function(x) paste0('log_rw_pred[', x, ']'))
  util$plot_conn_pushforward_quantiles(samples, names, data$years[idxs_t],
                                       xlab="", ylab='log_rw_pred', main = paste0('Tree ', data$uniq_tree_ids[t]),
                                       display_ylim=c(-10, 2), display_xlim = c(1980, 2021))
  points(data$years[idxs_t], data$log_rw_obs[idxs_t], pch=16, cex=1, col="white")
  points(data$years[idxs_t], data$log_rw_obs[idxs_t], pch=16, cex=0.6, col="black")
  abline(v = 2002, lty = 3, col="darkgrey")
  
  
  names <- sapply(idxs_t,
                  function(x) paste0('delta_sck[', x, ']'))
  util$plot_conn_pushforward_quantiles(samples, names, data$years[idxs_t],
                                       xlab="", ylab='delta_sck', 
                                       display_ylim=c(-10, 2), display_xlim = c(1980, 2021))
  abline(v = 2002, lty = 3, col="darkgrey")
  
  names <- sapply(1:43,
                  function(x) paste0('f_sh[', data$stand_idxs[t],',',x, ']'))
  util$plot_conn_pushforward_quantiles(samples, names, data$all_years,
                                       xlab="", ylab='Stand GP', 
                                       display_ylim=c(-2, 2), display_xlim = c(1980, 2021))
  abline(v = 2002, lty = 3, col="darkgrey")
}

```

### Stand 2

```{r}
#| fig-width: 8
#| fig-height: 4.7

par(mfcol = c(2,2))
for(t in 41:48){
  idxs_t <- data$tree_start_idxs[t]:data$tree_end_idxs[t]
  # names <- sapply(idxs_t,
  #                 function(x) paste0('log_rw_pred[', x, ']'))
  # util$plot_conn_pushforward_quantiles(samples, names, data$years[idxs_t],
  #                                      xlab="", ylab='log_rw_pred', main = paste0('Tree ', data$uniq_tree_ids[t]),
  #                                      display_ylim=c(-10, 2), display_xlim = c(1980, 2021))
  # points(data$years[idxs_t], data$log_rw_obs[idxs_t], pch=16, cex=1, col="white")
  # points(data$years[idxs_t], data$log_rw_obs[idxs_t], pch=16, cex=0.6, col="black")
  # abline(v = 2002, lty = 3, col="darkgrey")
  # 
  
  names <- sapply(idxs_t,
                  function(x) paste0('sck_state[', x, ']'))
  util$plot_conn_pushforward_quantiles(samples, names, data$years[idxs_t],
                                       xlab="", ylab='sck_state', 
                                       display_ylim=c(-0.1, 1.1), display_xlim = c(1980, 2021))
  abline(v = 2002, lty = 3, col="darkgrey")
  
  names <- sapply(1:43,
                  function(x) paste0('f_sh[', data$stand_idxs[t],',',x, ']'))
  util$plot_conn_pushforward_quantiles(samples, names, data$all_years,
                                       xlab="", ylab='Stand GP', 
                                       display_ylim=c(-2, 2), display_xlim = c(1980, 2021))
  abline(v = 2002, lty = 3, col="darkgrey")
}

```