---
title: "Tree Ring Data Visualization"
format: html
editor: visual
---

## Histograms of ringwidth

#### Alberta

```{r}
alberta <- read.csv("alberta.csv", header=TRUE)

hist(alberta$Ring_width.mm., main="Observed ringwidth across all trees and years in Alberta", xlab="Ring Width (mm)", col="green")
```

#### Arizona

```{r}
arizonabog <- read.csv("arizonabog.csv", header=TRUE)
arizonadec <- read.csv("arizonadec.csv", header=TRUE)
arizonaPIPO <- read.csv("arizonaPIPO.csv", header=TRUE)

#append arizona data sets into one
arizona <- rbind(arizonabog, arizonadec, arizonaPIPO)

hist(arizona$Ring_width.mm., main="Observed ringwidth across all trees and years in Arizona", xlab="Ring Width (mm)", col="green")
```

#### British Columbia

```{r}
bc <- read.csv("bc.csv", header=TRUE)

#filter out all data from 2023 (no ringwidth was recorded and all the input says "999" which skews the histogram)

filter_out_999 <- subset(bc, Ring_width.mm. != 999)

hist(filter_out_999$Ring_width.mm., main="Observed ringwidth across all trees and years in British Columbia", xlab="Ring Width (mm)", col="green")
```

#### Colorado

```{r}
coloradoclemons <- read.csv("coloradoclemons.csv", header=TRUE)

coloradobirch <- read.csv("coloradobonanzacreekbirch.csv", header=TRUE)

coloradospruce <- read.csv("coloradobonanzacreekspruce.csv", header=TRUE)

coloradocolumbine <- read.csv("coloradocolumbine.csv", header=TRUE)

coloradoduke <- read.csv("coloradoduke.csv", header=TRUE)

coloradoLPP <- read.csv("coloradoLPP.csv", header=TRUE)



#subset datasets into only the needed columns
subset_coloradoclemons <- coloradoclemons[, c("X","Ring_width.mm.")]

subset_coloradobirch <- coloradobirch[, c("X","Ring_width.mm.")]

subset_coloradospruce <- coloradospruce[, c("X","Ring_width.mm.")]

subset_coloradocolumbine <- coloradocolumbine[, c("X","Ring_width.mm.")]

subset_coloradoduke <- coloradoduke[, c("X","Ring_width.mm.")]

subset_coloradoLPP <- coloradoLPP[, c("X","Ring_width.mm.")]


#append all colorado datasets into one
colorado <- rbind(subset_coloradoclemons, subset_coloradobirch, subset_coloradospruce, subset_coloradocolumbine, subset_coloradoduke, subset_coloradoLPP)

hist(colorado$Ring_width.mm., main="Observed ringwidth across all trees and years in Colorado", xlab="Ring Width (mm)", col="green")

```

#### New Mexico

```{r}
newmexico <- read.csv("newmexico.csv", header=TRUE)

hist(newmexico$Ring_width.mm., main="Observed ringwidth across all trees and years in New Mexico", xlab="Ring Width (mm)", col="green")
```

#### Utah

```{r}
utah <- read.csv("utah.csv", header=TRUE)

hist(utah$Ring_width.mm., main="Observed ringwidth across all trees and years in Utah", xlab="Ring Width (mm)", col="green")
```

#### Idaho

```{r}
idaho <- read.csv("idaho.csv", header=TRUE)

hist(idaho$Ring_width.mm., main="Observed ringwidth across all trees and years in Idaho", xlab="Ring Width (mm)", col="green")
```

#### Montana

```{r}
montanacore <- read.csv("montanacore.csv", header=TRUE)
montanagrowth <- read.csv("montanagrowth.csv", header=TRUE)
ACRUm <- read.csv("ACRUmesic.csv", header=TRUE)
ACRUup <- read.csv("ACRUupslope.csv", header=TRUE)
BELEm <- read.csv("BELEmesic.csv", header=TRUE)
LITUm <- read.csv("LITUmesic.csv", header=TRUE)
LITUup <- read.csv("LITUupslope.csv", header=TRUE)
QUALm <- read.csv("QUALmesic.csv", header=TRUE)
QUALup <- read.csv("QUALupslope.csv", header=TRUE)
QUMOm <- read.csv("QUMOmesic.csv", header=TRUE)
QUMOup <- read.csv("QUMOupslope.csv", header=TRUE)
QURUm <- read.csv("QURUmesic.csv", header=TRUE)
QURUup <- read.csv("QURUupslope.csv", header=TRUE)


#subset datasets into only the needed columns
subset_montanacore <- montanacore[, c("X","Ring_width.mm.")]
subset_montanagrowth <- montanagrowth[, c("X","Ring_width.mm.")]
subset_ACRUm <- ACRUm[, c("X","Ring_width.mm.")]
subset_ACRUup <- ACRUup[, c("X","Ring_width.mm.")]
subset_BELEm <- BELEm[, c("X","Ring_width.mm.")]
subset_LITUm <- LITUm[, c("X","Ring_width.mm.")]
subset_LITUup <- LITUup[, c("X","Ring_width.mm.")]
subset_QUALm <- QUALm[, c("X","Ring_width.mm.")]
subset_QUALup <- QUALup[, c("X","Ring_width.mm.")]
subset_QUMOm <- QUMOm[, c("X","Ring_width.mm.")]
subset_QUMOup <- QUMOup[, c("X","Ring_width.mm.")]
subset_QURUm <- QURUm[, c("X","Ring_width.mm.")]
subset_QURUup <- QURUup[, c("X","Ring_width.mm.")]


#append all montana datasets into one
montana <- rbind(subset_montanacore, subset_montanagrowth, subset_ACRUm, subset_ACRUup, subset_BELEm, subset_LITUm, subset_LITUup, subset_QUALm, subset_QUALup, subset_QUMOm, subset_QUMOup, subset_QURUm, subset_QURUup)

hist(montana$Ring_width.mm., main="Observed ringwidth across all trees and years in Montana", xlab="Ring Width (mm)", col="green")
```

#### Nevada

```{r}
nevadasantarosa <- read.csv("nevadasantarosa.csv", header=TRUE)
nevadaruby <- read.csv("nevadaruby.csv", header=TRUE)
nevadajarbidge <- read.csv("nevadajarbidge.csv", header=TRUE)

#append all nevada datasets into one
nevada <- rbind(nevadasantarosa, nevadaruby, nevadajarbidge)

hist(nevada$Ring_width.mm., main="Observed ringwidth across all trees and years in Nevada", xlab="Ring Width (mm)", col="green")
```

#### Others

```{r}
CO_ABLA <- read.csv("others_CO_ABLA.csv", header=TRUE)
CO_PIPO <- read.csv ("others_CO_PIPO.csv", header=TRUE)
CO_POTR <- read.csv("others_CO_POTR.csv", header=TRUE)

#append all CO datasets into one
CO <- rbind(CO_ABLA, CO_PIPO, CO_POTR)

hist(CO$Ring_width.mm., main="Observed ringwidth across all trees and years", xlab="Ring Width (mm)", col="green")
```

```{r}
MT_ABLA <- read.csv("others_MT_ABLA.csv", header=TRUE)
MT_PSME <- read.csv("others_MT_PSME.csv", header=TRUE)
MT_TSHE <- read.csv("others_MT_TSHE.csv", header=TRUE)

#append all MT datasets into one
MT <- rbind(MT_ABLA, MT_PSME, MT_TSHE)

hist(MT$Ring_width.mm., main="Observed ringwidth across all trees and years", xlab="Ring Width (mm)", col="green")
```

```{r}
WA_ABLA <- read.csv("others_WA_ABLA.csv", header=TRUE)
WA_PSME <- read.csv("others_WA_PSME.csv", header=TRUE)
WA_TSHE <- read.csv("others_WA_TSHE.csv", header=TRUE)

#append all WA datasets into one
WA <- rbind(WA_ABLA, WA_PSME, WA_TSHE)

hist(WA$Ring_width.mm., main="Observed ringwidth across all trees and years", xlab="Ring Width (mm)", col="green")
```

## Tree-Level Time Series

#### Alberta

```{r}

I001013 <- subset(alberta, Tag == "I001013")

plot(I001013$years, y = I001013$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of I001013 Tag Over Time")

I131953 <- subset(alberta, Tag == "I131953")

plot(I131953$years, y = I131953$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of I131953 Tag Over Time")
```

#### Arizona

```{r}
isla1 <- subset(arizonabog, Tag == "isla1")

plot(isla1$years, y = isla1$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of isla1 Tag Over Time")

b5r1_6 <- subset(arizonadec, Tag == "b5r1_6")

plot(b5r1_6$years, y = b5r1_6$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of b5r1_6 Tag Over Time")

a295714098489998 <- subset(arizonaPIPO, Tag == "295714098489998")

plot(a295714098489998$years, y = a295714098489998$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of 295714098489998 Tag Over Time")
```

#### British Columbia

```{r}
b0331PMN <- subset(filter_out_999, Tag == "0331PMN")

plot(b0331PMN$years, y = b0331PMN$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of 0331PMN Tag Over Time")

b6320PCN <- subset(filter_out_999, Tag == "6320PCN")

plot(b6320PCN$years, y = b6320PCN$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of 6320PCN Tag Over Time")
```

#### Colorado

```{r}

c28PienD6 <- subset(coloradoclemons, Tag == "28PienD6")

plot(c28PienD6$years, y = c28PienD6$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of 28PienD6 Tag Over Time")

MURPH24 <- subset(coloradobirch, Tag == "MURPH24")

plot(MURPH24$years, y = MURPH24$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of MURPH24 Tag Over Time")

MDPg33 <- subset(coloradospruce, Tag == "MDPg33")

plot(MDPg33$years, y = MDPg33$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of MDPg33 Tag Over Time")

LCU01A <- subset(coloradocolumbine, Tag == "LCU01A")

plot(LCU01A$years, y = LCU01A$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of LCU01A Tag Over Time")

pigl2273a <- subset(coloradoduke, Tag == "pigl2273a")

plot(pigl2273a$years, y = pigl2273a$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of pigl2273a Tag Over Time")

c35M22 <- subset(coloradoLPP, Tag == "35M22")

plot(c35M22$years, y = c35M22$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of 35M22 Tag Over Time")
```

#### New Mexico

```{r}
BNF0702130930SF <- subset(newmexico, Tag == "BNF0702130930SF")

plot(BNF0702130930SF$years, y = BNF0702130930SF$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of BNF0702130930SF Tag Over Time")
```

#### Utah

```{r}
u2928625010690_2928639010690 <- subset(utah, Tag == "2928625010690-2928639010690")

plot(u2928625010690_2928639010690$years, y = u2928625010690_2928639010690$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of 2928625010690-2928639010690 Tag Over Time")
```

#### Idaho

```{r}
verd_9 <- subset(idaho, Tag == "verd_9")

plot(verd_9$years, y = verd_9$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of verd_9 Tag Over Time")
```

#### Montana

```{r}

a3r1_10 <- subset(montanacore, Tag == "a3r1_10")

plot(a3r1_10$years, y = a3r1_10$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of a3r1_10 Tag Over Time")

LSWL1 <- subset(montanagrowth, Tag == "LSWL1")

plot(LSWL1$years, y = LSWL1$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of LSWL1 Tag Over Time")

WR.11 <- subset(ACRUm, Tag == "WR.11")

plot(WR.11$years, y = WR.11$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of WR.11 Tag Over Time")

dc.318 <- subset(ACRUup, Tag == "dc.318")

plot(dc.318$years, y = dc.318$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of dc.318 Tag Over Time")

pm.861 <- subset(BELEm, Tag == "pm.861")

plot(pm.861$years, y = pm.861$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of pm.861 Tag Over Time")

PB.1 <- subset(LITUm, Tag == "PB.1")

plot(PB.1$years, y = PB.1$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of PB.1 Tag Over Time")

HCL.2 <- subset(LITUup, Tag == "HCL.2")

plot(HCL.2$years, y = HCL.2$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of HCL.2 Tag Over Time")

CC.19 <- subset(QUALm, Tag == "CC.19")

plot(CC.19$years, y = CC.19$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of CC.19 Tag Over Time")

dc.230 <- subset(QUALup, Tag == "dc.230")

plot(dc.230$years, y = dc.230$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of dc.230 Tag Over Time")

pr.948 <- subset(QUMOm, Tag == "pr.948")

plot(pr.948$years, y = pr.948$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of pr.948 Tag Over Time")

USF.16 <- subset(QUMOup, Tag == "USF.16")

plot(USF.16$years, y = USF.16$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of USF.16 Tag Over Time")

jc.179 <- subset(QURUm, Tag == "jc.179")

plot(jc.179$years, y = jc.179$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of jc.179 Tag Over Time")

dc.237 <- subset(QURUup, Tag == "dc.237")

plot(dc.237$years, y = dc.237$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of dc.237 Tag Over Time")
```

#### Nevada

```{r}

SR434326 <- subset(nevadasantarosa, Tag == "SR434326")

plot(SR434326$years, y = SR434326$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of SR434326 Tag Over Time")

RB493012 <- subset(nevadaruby, Tag == "RB493012")

plot(RB493012$years, y = RB493012$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of RB493012 Tag Over Time")

JB118320 <- subset(nevadajarbidge, Tag == "JB118320")

plot(JB118320$years, y = JB118320$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of JB118320 Tag Over Time")
```

#### Others

```{r}
ABLA_H_01H <- subset(CO, Tag == "ABLA-H-01H")

plot(ABLA_H_01H$years, y = ABLA_H_01H$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of ABLA-H-01H Tag Over Time")

PIPO_M_8L <- subset(CO, Tag == "PIPO-M-8L")

plot(PIPO_M_8L$years, y = PIPO_M_8L$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of PIPO-M-8L Tag Over Time")

POTR_M_3L <- subset(CO, Tag == "POTR-M-3L")

plot(POTR_M_3L$years, y = POTR_M_3L$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of POTR-M-3L Tag Over Time")
```

```{r}
ABLA_H_10C <- subset(MT, Tag == "ABLA-H-10C")

plot(ABLA_H_10C$years, y = ABLA_H_10C$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of ABLA-H-10C Tag Over Time")

PSME_M_11N <- subset(MT, Tag == "PSME-M-11N")

plot(PSME_M_11N$years, y = PSME_M_11N$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of PSME-M-11N Tag Over Time")

TSHE_M_08C <- subset(MT, Tag == "TSHE-M-08C")

plot(TSHE_M_08C$years, y = TSHE_M_08C$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of TSHE-M-08C Tag Over Time")
```

```{r}
ABLA_H_10C <- subset(WA, Tag == "ABLA-H-10C")

plot(ABLA_H_10C$years, y = ABLA_H_10C$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of ABLA-H-10C Tag Over Time")

PSME_M_9N <- subset(WA, Tag == "PSME-M-9N")

plot(PSME_M_9N$years, y = PSME_M_9N$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of PSME-M-9N Tag Over Time")

TSHE_H_10C <- subset(WA, Tag == "TSHE-H-10C")

plot(TSHE_H_10C$years, y = TSHE_H_10C$Ring_width.mm., type = "o", col="darkgreen", xlab= "Time (in years)", ylab = "Ring Width (mm)", main = "Ring Width of TSHE-H-10C Tag Over Time")
```
